"""Public interface for the HIL-RIG host-side API."""

from hilrig.api import (
    I2C,
    SPI,
    UART,
    AnalogueOutput,
    DigitalInput,
    DigitalInputExpectation,
    DigitalOutput,
    PwmInput,
    PwmOutput,
    Test,
)
from hilrig.exceptions import (
    ConfigurationError,
    FrozenTestError,
    HilRigError,
    PeripheralError,
    TimingError,
    ValidationError,
)
from hilrig.models.configuration import (
    DigitalState,
    FrequencyMode,
    I2CRole,
    I2CSpeed,
    LogicVoltage,
    Pullup,
    SPIBaud,
    SPIFirst,
    SPIMode,
    SPIRole,
    SPISize,
    StartMode,
    UARTLengthBits,
    UARTMode,
    UARTParity,
    UARTStopBits,
)
from hilrig.models.execution import CompiledTestIR

__all__ = [
    "AnalogueOutput",
    "ConfigurationError",
    "CompiledTestIR",
    "DigitalInput",
    "DigitalInputExpectation",
    "DigitalOutput",
    "DigitalState",
    "FrequencyMode",
    "FrozenTestError",
    "HilRigError",
    "I2C",
    "I2CRole",
    "I2CSpeed",
    "LogicVoltage",
    "PeripheralError",
    "Pullup",
    "PwmInput",
    "PwmOutput",
    "SPI",
    "SPIBaud",
    "SPIFirst",
    "SPIMode",
    "SPIRole",
    "SPISize",
    "StartMode",
    "Test",
    "TimingError",
    "UART",
    "UARTLengthBits",
    "UARTMode",
    "UARTParity",
    "UARTStopBits",
    "ValidationError",
]
